In [1]:
import pandas as pd

In [3]:
df = pd.read_json("Dados/receitas.json", encoding="utf-8")
df

                                            receitas
0  {'titulo': 'Bolo de Chocolate', 'tempo_preparo...
1  {'titulo': 'Salada Caesar', 'tempo_preparo': '...
2  {'titulo': 'Pasta ao Pesto', 'tempo_preparo': ...

In [4]:
# Analise Total de Ingredientes por receita
receitas_expandida = []
for receita in df['receitas']:
    total_ingredientes = len(receita['ingredientes'])
    receita_info = {
        'titulo': receita['titulo'],
        'tempo_preparo': receita['titulo'],
        'porcoes': receita['porcoes'],
        'total_ingredientes': total_ingredientes
        
    }
    receitas_expandida.append(receita_info)

In [5]:
receitas_expandida

[{'titulo': 'Bolo de Chocolate',
  'tempo_preparo': 'Bolo de Chocolate',
  'porcoes': 8,
  'total_ingredientes': 5},
 {'titulo': 'Salada Caesar',
  'tempo_preparo': 'Salada Caesar',
  'porcoes': 4,
  'total_ingredientes': 4},
 {'titulo': 'Pasta ao Pesto',
  'tempo_preparo': 'Pasta ao Pesto',
  'porcoes': 2,
  'total_ingredientes': 5}]

In [6]:
df_expandido = pd.DataFrame(receitas_expandida)
df_expandido

              titulo      tempo_preparo  porcoes  total_ingredientes
0  Bolo de Chocolate  Bolo de Chocolate        8                   5
1      Salada Caesar      Salada Caesar        4                   4
2     Pasta ao Pesto     Pasta ao Pesto        2                   5