In [16]:
import pandas as pd

In [17]:
dados = {
    'Times': ['Flamengo', 'Palmeiras', 'São Paulo', 'Santos', 'Corinthians'],
    'Partidas_Jogadas': [10, 10, 10, 10, 10],
    'Vitorias': [7, 5, 6, 4, 3],
    'Empates': [2, 3, 1, 3, 2],
    'Derrotas': [1, 2, 3, 3, 5],
    'Gols_Pro': [22, 18, 16, 14, 10],
    'Gols_Contra': [10, 12, 15, 16, 7]  
}

In [18]:
df = pd.DataFrame(dados)
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra
0,Flamengo,10,7,2,1,22,10
1,Palmeiras,10,5,3,2,18,12
2,São Paulo,10,6,1,3,16,15
3,Santos,10,4,3,3,14,16
4,Corinthians,10,3,2,5,10,7

In [19]:
df['Saldo_Gols'] = df['Gols_Pro'] - df['Gols_Contra']
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols
0,Flamengo,10,7,2,1,22,10,12
1,Palmeiras,10,5,3,2,18,12,6
2,São Paulo,10,6,1,3,16,15,1
3,Santos,10,4,3,3,14,16,-2
4,Corinthians,10,3,2,5,10,7,3

In [20]:
df['Pontos'] = df['Vitorias'] * 3 + df['Empates'] * 1
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,Palmeiras,10,5,3,2,18,12,6,18
2,São Paulo,10,6,1,3,16,15,1,19
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,7,3,11

In [21]:
df = df.sort_values(by='Pontos',  ascending=False)
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
2,São Paulo,10,6,1,3,16,15,1,19
1,Palmeiras,10,5,3,2,18,12,6,18
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,7,3,11

In [23]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [24]:
df.to_excel("Dados/campeonato_futebol.xlsx", index=False)